name: automated_deploy_to_ec2

on:
  push:
    branches:
      - 'main'

jobs:
  django_test:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install python packages
      run: pip install -r requirements.txt

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: 6.0
        mongodb-port: 27017

    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: 7
        redis-port: 6379

    - name: Django test
      run: python manage.py test

  deploy_to_ec2:
    runs-on: ubuntu-latest
    needs: django_test
    steps:
      - name: Docker compose on EC2
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOSTNAME }}
          user: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command: |
            cd /home/ec2-user/delivery_fee_calculator_backend
            git pull
            docker compose up -d --build
